name: Continuous Integration
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Setup-java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin
      - name: Build
        run: ./gradlew check